In [334]:
import pandas as pd

file_path = "../data/raw/All data.xlsx"

df = pd.read_excel(file_path)

print(df.shape)
df.head()

(9392, 29)

,Local time in Rabat (airport),T,Po,P,Pa,U,DD,Ff,ff10,ff3,...,Cm,Ch,VV,Td,RRR,tR,E,Tg,E',sss
0,29.03.2022 09:00,16.0,751.3,757.6,0.5,99.0,Wind blowing from the north,2.0,NaN,NaN,...,Altocumulus translucidus or opacus in two or m...,"No Cirrus, Cirrocumulus or Cirrostratus.",5,15.8,0.3,3.0,NaN,NaN,NaN,NaN
1,29.03.2022 06:00,15.2,750.8,757.1,-0.2,99.0,"Calm, no wind",0.0,NaN,NaN,...,Altocumulus translucidus at a single level.,NaN,5,15.1,0.9,24.0,NaN,NaN,NaN,NaN
2,29.03.2022 03:00,13.3,751.0,757.3,-1.5,99.0,"Calm, no wind",0.0,NaN,NaN,...,Altocumulus translucidus at a single level.,"No Cirrus, Cirrocumulus or Cirrostratus.",5,13.1,No precipitation,3.0,NaN,NaN,NaN,NaN
3,29.03.2022 00:00,14.6,752.5,758.9,-1.0,99.0,"Calm, no wind",0.0,NaN,NaN,...,Altocumulus translucidus at a single level.,"No Cirrus, Cirrocumulus or Cirrostratus.",5,14.4,No precipitation,6.0,NaN,NaN,NaN,NaN
4,28.03.2022 21:00,15.4,753.5,759.9,1.4,99.0,Wind blowing from the south-west,2.0,NaN,NaN,...,"No Altocumulus, Altostratus or Nimbostratus.","No Cirrus, Cirrocumulus or Cirrostratus.",5,15.3,No precipitation,3.0,NaN,NaN,NaN,NaN

In [335]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9392 entries, 0 to 9391
Data columns (total 29 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Local time in Rabat (airport)  9392 non-null   str
 1   T                              9388 non-null   float64
 2   Po                             9386 non-null   float64
 3   P                              9384 non-null   float64
 4   Pa                             9263 non-null   float64
 5   U                              9386 non-null   float64
 6   DD                             9388 non-null   str
 7   Ff                             9388 non-null   float64
 8   ff10                           81 non-null     float64
 9   ff3                            406 non-null    float64
 10  N                              9353 non-null   str
 11  WW                             9392 non-null   str
 12  W1                             871 non-null    str
 13  W2                             870 non-null    str
 14  Tn                             1167 non-null   float64
 15  Tx                             1172 non-null   float64
 16  Cl                             7113 non-null   str
 17  Nh                             7120 non-null   str
 18  H                              7170 non-null   str
 19  Cm                             6437 non-null   str
 20  Ch                             5850 non-null   str
 21  VV                             9390 non-null   object
 22  Td                             9388 non-null   float64
 23  RRR                            7937 non-null   object
 24  tR                             7937 non-null   float64
 25  E                              0 non-null      float64
 26  Tg                             0 non-null      float64
 27  E'                             0 non-null      float64
 28  sss                            0 non-null      float64
dtypes: float64(16), object(2), str(11)
memory usage: 2.1+ MB

In [336]:
column_mapping = {
    "Local time in Rabat (airport)": "timestamp",
    "T": "temperature_c",
    "Po": "station_pressure_hpa",
    "P": "sea_level_pressure_hpa",
    "Pa": "pressure_change_hpa",
    "U": "humidity_pct",
    "DD": "wind_direction",
    "Ff": "wind_speed_ms",
    "ff10": "wind_gust_10min_ms",
    "ff3": "wind_gust_3sec_ms",
    "N": "cloud_cover",
    "WW": "present_weather_code",
    "W1": "past_weather_code_1",
    "W2": "past_weather_code_2",
    "Tn": "min_temperature_c",
    "Tx": "max_temperature_c",
    "Cl": "low_cloud_type",
    "Nh": "cloud_amount",
    "H": "cloud_base_height",
    "Cm": "middle_cloud_type",
    "Ch": "high_cloud_type",
    "VV": "visibility",
    "Td": "dew_point_c",
    "RRR": "precipitation_mm",
    "tR": "precipitation_period_h",
    "E": "ground_condition",
    "Tg": "ground_temperature_c",
    "E'": "ground_state",
    "sss": "snow_depth"
}
df = df.rename(columns=column_mapping)

In [337]:
duplicates = df.duplicated().sum()

print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [338]:
df["timestamp"].duplicated().sum()

np.int64(0)

In [339]:
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing

ground_condition          9392
snow_depth                9392
ground_state              9392
ground_temperature_c      9392
wind_gust_10min_ms        9311
wind_gust_3sec_ms         8986
past_weather_code_2       8522
past_weather_code_1       8521
min_temperature_c         8225
max_temperature_c         8220
high_cloud_type           3542
middle_cloud_type         2955
low_cloud_type            2279
cloud_amount              2272
cloud_base_height         2222
precipitation_mm          1455
precipitation_period_h    1455
pressure_change_hpa        129
cloud_cover                 39
sea_level_pressure_hpa       8
humidity_pct                 6
station_pressure_hpa         6
temperature_c                4
wind_direction               4
wind_speed_ms                4
dew_point_c                  4
visibility                   2
present_weather_code         0
timestamp                    0
dtype: int64

In [340]:
missing_pct = (df.isna().sum() / len(df) * 100).sort_values(ascending=False)

missing_pct

ground_condition          100.000000
snow_depth                100.000000
ground_state              100.000000
ground_temperature_c      100.000000
wind_gust_10min_ms         99.137564
wind_gust_3sec_ms          95.677172
past_weather_code_2        90.736797
past_weather_code_1        90.726150
min_temperature_c          87.574532
max_temperature_c          87.521295
high_cloud_type            37.712947
middle_cloud_type          31.462947
low_cloud_type             24.265332
cloud_amount               24.190801
cloud_base_height          23.658433
precipitation_mm           15.491908
precipitation_period_h     15.491908
pressure_change_hpa         1.373509
cloud_cover                 0.415247
sea_level_pressure_hpa      0.085179
humidity_pct                0.063884
station_pressure_hpa        0.063884
temperature_c               0.042589
wind_direction              0.042589
wind_speed_ms               0.042589
dew_point_c                 0.042589
visibility                  0.021295
present_weather_code        0.000000
timestamp                   0.000000
dtype: float64

In [341]:
columns_to_drop = [
    "ground_condition",
    "snow_depth",
    "ground_state",
    "ground_temperature_c",
    "wind_gust_10min_ms",
    "wind_gust_3sec_ms",
    "past_weather_code_1",
    "past_weather_code_2"
]

df = df.drop(columns=columns_to_drop)

print("Remaining columns:", len(df.columns))

Remaining columns: 21

In [342]:
df["precipitation_mm"].value_counts(dropna=False)

precipitation_mm
No precipitation          6696
NaN                       1455
0.1                        556
2                           78
3                           73
0.2                         67
1                           52
5                           51
0.3                         46
4                           41
0.4                         32
0.9                         25
6                           22
0.6                         20
7                           19
0.5                         18
0.8                         18
8                           15
0.7                         12
9                           12
10                          11
12                          10
13                           7
11                           7
24                           6
Trace of precipitation       5
14                           4
27                           3
19                           3
15                           3
16                           3
21                           2
17                           2
30                           2
25                           1
150                          1
36                           1
32                           1
18                           1
58                           1
39                           1
55                           1
28                           1
20                           1
34                           1
26                           1
43                           1
37                           1
69                           1
40                           1
Name: count, dtype: int64

In [343]:
df["precipitation_mm"] = (
    df["precipitation_mm"]
      .replace("No precipitation", 0)
      .replace("Trace of precipitation", 0.01)
)

df["precipitation_mm"] = pd.to_numeric(
    df["precipitation_mm"],
    errors="coerce"
)

df["precipitation_mm"] = df["precipitation_mm"].fillna(0)

df["precipitation_mm"].describe()

count    9392.000000
mean        0.338155
std         2.703872
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       150.000000
Name: precipitation_mm, dtype: float64

In [344]:
df["precipitation_period_h"] = (
    df["precipitation_period_h"]
      .fillna(0)
)

In [345]:
continuous_cols = [
    "temperature_c",
    "humidity_pct",
    "station_pressure_hpa",
    "sea_level_pressure_hpa",
    "pressure_change_hpa",
    "wind_speed_ms",
    "dew_point_c",
    "visibility"
]
for col in continuous_cols:
    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

for col in continuous_cols:
    df[col] = df[col].interpolate()

In [346]:
df[[
    "temperature_c",
    "min_temperature_c",
    "max_temperature_c"
]].head(30)

    temperature_c  min_temperature_c  max_temperature_c
0            16.0                NaN                NaN
1            15.2               12.9                NaN
2            13.3                NaN                NaN
3            14.6                NaN                NaN
4            15.4                NaN                NaN
5            17.8                NaN               23.3
6            20.2                NaN                NaN
7            20.8                NaN                NaN
8            21.1                NaN                NaN
9            17.9               12.9                NaN
10           16.9                NaN                NaN
11           13.1                NaN                NaN
12           15.4                NaN                NaN
13           19.3                NaN               25.1
14           23.1                NaN                NaN
15           24.1                NaN                NaN
16           17.6                NaN                NaN
17           10.6                7.5                NaN
18            8.8                NaN                NaN
19           11.9                NaN                NaN
20           13.5                NaN                NaN
21           16.5                NaN               19.3
22           18.8                NaN                NaN
23           18.3                NaN                NaN
24           15.2                NaN                NaN
25           13.5               12.3                NaN
26           12.4                NaN                NaN
27           13.0                NaN                NaN
28           14.2                NaN               18.6
29           16.1                NaN                NaN

In [347]:
df = df.drop(
    columns=[
        "min_temperature_c",
        "max_temperature_c"
    ]
)

print(df.shape)

(9392, 19)

In [348]:
df = df.drop(
    columns=[
        "high_cloud_type",
        "middle_cloud_type",
        "low_cloud_type"
    ]
)

In [349]:
df[["cloud_amount", "cloud_base_height"]].dtypes

cloud_amount         str
cloud_base_height    str
dtype: object

In [350]:
df = df.drop(
    columns=[
        "cloud_amount",
        "cloud_base_height"
    ]
)

In [351]:
sorted(df["cloud_cover"].dropna().unique())
df["cloud_cover"].value_counts(dropna=False)

cloud_cover
no clouds                    2219
70 – 80%.                    1332
40%.                         1279
60%.                         1278
50%.                         1002
90  or more, but not 100%     806
20–30%.                       755
100%.                         623
10%  or less, but not 0        59
NaN                            39
Name: count, dtype: int64

In [352]:
# Normalize cloud cover strings

df["cloud_cover"] = (
    df["cloud_cover"]
      .astype(str)
      .str.strip()
      .str.replace("–", "-", regex=False)
      .str.replace("  ", " ", regex=False)
)

cloud_mapping = {
    "no clouds": 0,
    "10% or less, but not 0": 1,
    "20-30%": 2,
    "40%": 3,
    "50%": 4,
    "60%": 5,
    "70 - 80%": 6,
    "90 or more, but not 100%": 7,
    "100%": 8
}

df["cloud_cover_encoded"] = (
    df["cloud_cover"]
    .map(cloud_mapping)
)

In [353]:
df["cloud_cover_encoded"] = (
    df["cloud_cover_encoded"]
    .fillna(df["cloud_cover_encoded"].median())
)

In [ ]:
df = df.drop(columns=["cloud_cover"])

In [354]:
df["wind_direction"] = (
    df["wind_direction"]
      .replace("ffill", pd.NA)
      .ffill()
)

In [355]:
sorted(df["wind_direction"].dropna().unique())

['Calm, no wind',
 'Wind blowing from the east',
 'Wind blowing from the east-northeast',
 'Wind blowing from the east-southeast',
 'Wind blowing from the north',
 'Wind blowing from the north-east',
 'Wind blowing from the north-northeast',
 'Wind blowing from the north-northwest',
 'Wind blowing from the north-west',
 'Wind blowing from the south',
 'Wind blowing from the south-east',
 'Wind blowing from the south-southeast',
 'Wind blowing from the south-southwest',
 'Wind blowing from the south-west',
 'Wind blowing from the west',
 'Wind blowing from the west-northwest',
 'Wind blowing from the west-southwest']

In [356]:
wind_mapping = {
    "Calm, no wind": 0,
    "Wind blowing from the north": 0,
    "Wind blowing from the north-northeast": 22.5,
    "Wind blowing from the north-east": 45,
    "Wind blowing from the east-northeast": 67.5,
    "Wind blowing from the east": 90,
    "Wind blowing from the east-southeast": 112.5,
    "Wind blowing from the south-east": 135,
    "Wind blowing from the south-southeast": 157.5,
    "Wind blowing from the south": 180,
    "Wind blowing from the south-southwest": 202.5,
    "Wind blowing from the south-west": 225,
    "Wind blowing from the west-southwest": 247.5,
    "Wind blowing from the west": 270,
    "Wind blowing from the west-northwest": 292.5,
    "Wind blowing from the north-west": 315,
    "Wind blowing from the north-northwest": 337.5
}
df["wind_direction_deg"] = (
    df["wind_direction"]
    .map(wind_mapping)
)

In [357]:
import numpy as np

radians = np.deg2rad(df["wind_direction_deg"])

df["wind_dir_sin"] = np.sin(radians)
df["wind_dir_cos"] = np.cos(radians)

In [358]:
df=df.drop(columns=["wind_direction","wind_direction_deg"])

In [359]:
remaining_missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

remaining_missing

cloud_cover               39
timestamp                  0
station_pressure_hpa       0
temperature_c              0
sea_level_pressure_hpa     0
pressure_change_hpa        0
humidity_pct               0
wind_speed_ms              0
present_weather_code       0
visibility                 0
dew_point_c                0
precipitation_mm           0
precipitation_period_h     0
cloud_cover_encoded        0
wind_dir_sin               0
wind_dir_cos               0
dtype: int64